CREATE TABLE IF NOT EXISTS datos(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parameters text NOT NULL CHECK (parameters <> ''), 
    shoping_centers text NOT NULL CHECK (shoping_centers <> ''), 
    roads text NOT NULL CHECK (roads <> ''), 
    minimum_time integer, 
    creation_date timestamp NOT NULL DEFAULT NOW()
);

INSERT INTO datos(parameters, shoping_centers, roads, minimum_time)
	VALUES ('5,5,5', '1,1-1,2-1,3-1,4-1,5', '1,2,10-1,3,10-2,4,10-3,5,10-4,5,10', 30);